"use strict";
// Operator guidance travels with the private authoring projection and its contracts.
module.exports = {
  "validationPassed": "Validation passed. All values use supported content contracts.",
  "previewPurpose": "Presentation preview. Use the separate draft playtest to exercise the saved mechanics in the production engine.",
  "cardPreview": "This card uses the published presentation contract. Changed labels or artwork are composed from this release’s references.",
  "metadataPreview": "Metadata preview. This domain has no standalone player component.",
  "unsavedPrompt": "Discard unsaved local form values? The saved shared draft will remain unchanged.",
  "publicationPending": "Publication saved in GitHub. The live release changes after its checks, merge and deployment.",
  "fieldSaved": "Field saved to the shared draft. Live content is unchanged.",
  "published": "Release published. Future games use this content.",
  "linesHelp": "One entry per line. Empty voice-file lines keep dialogue positions aligned.",
  "assetHelp": "Existing /assets/gauntlet/ reference; files are deployed with the client.",
  "revertPrompt": "Discard this field’s unsaved values and revert to live?",
  "emptySearch": " match this search. Clear or change the search to browse content.",
  "sharedDraft": "One shared draft across Content and Game. Saving a field leaves live content unchanged. ",
  "noDraft": "Save a field to create a draft before validating or previewing it.",
  "conflict": "The shared draft changed. Your local values were kept. Compare each saved shared draft value before retrying.",
  "retryReady": "Latest revision selected for retry. Review your values, then save again.",
  "connectionRequired": "Browsing live content. Saving and publishing are unavailable until GitHub is connected. Ask the hosting administrator to configure the connection, then choose Refresh admin.",
  "connectionSetup": "The backend needs GAUNTLET_GITHUB_TOKEN for this repository, with Contents and Pull requests write access and Checks and Commit statuses read access. Existing GITHUB_TOKEN or GH_TOKEN credentials are also supported. No persistent server disk is needed.",
  "unavailable": "Authoring is unavailable. Check the configured content provider.",
  "deploymentPending": "The current deployed release stays active until the new deployment completes.",
  "publishingHelp": "Validate and preview the saved draft, then publish one immutable release. GitHub publications and rollbacks take effect after deployment.",
  "releaseIdentity": "Advanced / Technical · active release and draft revision",
  "previewReady": "This saved draft has passed validation and is ready for presentation review in Content or Game.",
  "playtestRequired": "Playtest the saved mechanical draft in Content or Game before publishing.",
  "gameHelp": "Edit mode names, descriptions and shared hand size in the draft. Starting life, deck slots and mode behavior are read-only.",
  "contentHelp": "Compare live content with the shared draft below. Save each field before previewing or testing. Only supported mechanics are editable; protected fields are listed separately.",
  "readOnly": "This object controls engine behavior and is read-only.",
  "protectedFields": "Engine-controlled and derived fields · read-only",
  "engineHelp": "These identities and unsupported mechanics require an engine change. Displayed rules text does not change an effect.",
  "selectionPrompt": "Select an object to compare its live and draft fields.",
  "engineSource": "Read-only · shared/duel-rules/index.js and server/index.js",
  "previewSelection": "Preview prepared. Select an object to inspect its saved presentation.",
  "cancelHelp": "Close the unmerged publication and keep the shared draft for further editing.",
  "discardHelp": "This removes the saved draft for both administrators. Published releases remain available.",
  "publishHelp": "This changes content for future games after publication completes. GitHub releases and rollbacks must pass checks and deploy first. Running games keep their captured content; historical evidence is unchanged.",
  "replaceTest": "Replace this temporary playtest? Its evidence will be cleared.",
  "testIsolation": "Production engine · temporary session. No rewards, progression, ranked results or match-history entries. An accepted action records a receipt, not a completed match or balance assessment.",
  "factionLock": "This test uses the selected content's faction.",
  "combatScope": "Attack value is not damage dealt. Combat totals include resolved attack receipts only; healing and other life effects are in the event history.",
  "omittedEvents": " earlier events omitted; totals cover the whole session.",
  "testIdentity": "Advanced / Technical · engine state and pinned definitions",
  "receipt": "Engine action checked for this saved draft. This records an accepted action, not a completed match or a balance assessment.",
  "steps": "Edit → Save each field → Validate → Preview → Playtest → Revise → Review release",
  "unsavedReadiness": "Unsaved local values have not been validated or previewed.",
  "previewHelp": "Save and validate, then choose Preview saved draft above. Preview checks presentation; mechanics need an engine playtest.",
  "additionsHelp": "One copy per selected card, from this encounter's faction. The base deck stays engine-controlled.",
  "domains": {
    "campaigns": "Campaigns",
    "encounters": "Encounters",
    "factions": "Factions",
    "cards": "Cards",
    "decks": "Decks",
    "characters": "Characters / opponents",
    "assets": "Assets"
  }
};
