const { test, expect } = require("@playwright/test");
const AxeBuilder = require("@axe-core/playwright").default;

const loginSessions = new Map();
async function signIn(page, request, name) {
  if (!loginSessions.has(name)) {
    const response = await request.post("http://127.0.0.1:4117/api/auth/login", { data: { name, password: "test-password" } });
    expect(response.ok()).toBeTruthy();
    loginSessions.set(name, (await response.json()).token);
  }
  const token = loginSessions.get(name);
  await page.evaluate((value) => localStorage.setItem("gauntlet_auth_token", value), token);
  return token;
}

test("both authorized accounts can inspect every section; other accounts and guests cannot", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  await expect(page.getByRole("heading", { name: "Private administration" })).toBeVisible();
  expect((await request.get("http://127.0.0.1:4117/admin/gauntlet/content")).status()).toBe(401);
  await page.getByRole("button", { name: "Sign in through Identity" }).click();
  await page.getByPlaceholder("Account name", { exact: true }).fill("simply");
  await page.getByPlaceholder("Password", { exact: true }).fill("test-password");
  await page.getByRole("button", { name: "Sign In", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Gauntlet Admin", exact: true })).toBeVisible();
  const visitor = await signIn(page, request, "Visitor");
  await page.reload();
  await expect(page.getByRole("alert")).toContainText("does not have access");
  expect((await request.get("http://127.0.0.1:4117/api/admin/catalog", { headers: { Authorization: `Bearer ${visitor}` } })).status()).toBe(403);

  await signIn(page, request, "simply");
  await page.reload();
  await expect(page.getByRole("heading", { name: "Gauntlet Admin", exact: true })).toBeVisible();
  await page.getByText("Advanced / Technical · content and rules versions", { exact: true }).click();
  await expect(page.locator(".admin-facts").getByText(/^gauntlet-content-[a-f0-9]{64}$/)).toBeVisible();
  await page.getByText("Advanced / Technical · content and rules versions", { exact: true }).click();
  await page.screenshot({ path: "artifacts/admin-overview-desktop.png", fullPage: true });
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: /^Cards \d+\b/ }).click();
  await page.getByLabel("Search cards").fill("Capital Investment Spear");
  await page.getByRole("button", { name: "Inspect Capital Investment Spear", exact: true }).click();
  await page.getByText("Advanced / Technical · identity and source", { exact: true }).click();
  await expect(page.getByLabel("Selected content")).toContainText("server/gameContent.js");
  await page.getByText("Advanced / Technical · identity and source", { exact: true }).click();
  await page.screenshot({ path: "artifacts/admin-content-desktop.png", fullPage: true });
  await nav.getByText("Game", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Starting state" })).toBeVisible();
  await nav.getByText("Players", { exact: true }).click();
  await page.getByRole("button", { name: "View player simply", exact: true }).click();
  await expect(page.getByRole("region", { name: "Selected player" }).getByText("At a glance", { exact: true })).toBeVisible();
  await nav.getByText("Matches", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect match dddddddd-dddd-4ddd-8ddd-dddddddddddd", exact: true }).click();
  await expect(page.getByRole("heading", { name: /Authoritative audit history/ })).toBeVisible();
  await nav.getByText("Publishing", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Release history and rollback" })).toBeVisible();
  await nav.getByText("System", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Schema and rules versions" })).toBeVisible();
  const accessibility = await new AxeBuilder({ page }).include(".gauntlet-admin").analyze();
  expect(accessibility.violations).toEqual([]);

  await signIn(page, request, "Burnt Ramen");
  await page.reload();
  await expect(page.getByRole("heading", { name: "Gauntlet Admin", exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(nav.getByText("System", { exact: true })).toBeVisible();
  await page.screenshot({ path: "artifacts/admin-overview-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("player profiles keep records out of the summary and support focused browsing on desktop and phone", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  await signIn(page, request, "simply"); await page.reload();
  await page.getByRole("navigation", { name: "Administration sections" }).getByRole("button", { name: "Players", exact: true }).click();
  await page.getByRole("button", { name: "View player simply", exact: true }).click();
  const profile = page.getByRole("region", { name: "Selected player" });
  await expect(profile.getByRole("heading", { name: "simply", exact: true })).toBeFocused();
  await expect(profile.getByText("Account ID", { exact: true })).toHaveCount(0);
  await expect(profile.locator("pre")).toHaveCount(0);
  await page.screenshot({ path: "artifacts/admin-players-desktop.png", fullPage: true });
  const details = page.getByRole("navigation", { name: "Player details" });
  await details.getByRole("button", { name: "Campaigns", exact: true }).click();
  await profile.locator("summary").filter({ hasText: "Rumin" }).click();
  await expect(profile.getByText("Brothers of Destiny", { exact: true })).toBeVisible();
  await expect(profile.getByText("Cleared", { exact: true })).toBeVisible();
  await details.getByRole("button", { name: "Collection", exact: true }).click();
  await expect(profile.getByRole("heading", { name: "Collection & unlocks" })).toBeVisible();
  await details.getByRole("button", { name: "Decks", exact: true }).click();
  await expect(profile.getByRole("heading", { name: "Saved decks" })).toBeVisible();
  await details.getByRole("button", { name: "Technical", exact: true }).click();
  await expect(profile.getByText("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", { exact: true })).toBeVisible();
  await profile.getByText("Complete player record", { exact: true }).click();
  await expect(profile.locator("pre")).toContainText("matchReferences");
  await page.getByRole("button", { name: "View player Visitor", exact: true }).click();
  await expect(profile.getByText("At a glance", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByLabel("Filter this page")).toBeHidden();
  await page.screenshot({ path: "artifacts/admin-players-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect((await new AxeBuilder({ page }).include(".gauntlet-admin").analyze()).violations).toEqual([]);
  await profile.getByRole("button", { name: "Back to player list" }).click();
  await expect(page.getByLabel("Filter this page")).toBeFocused();
  await page.getByLabel("Filter this page").fill("simply");
  await expect(page.getByRole("button", { name: "View player Visitor", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "View player simply", exact: true })).toBeVisible();
});

test("only admins can save player metadata, with unsaved-change protection and persistent name updates", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const visitor = await signIn(page, request, "Visitor");
  const path = "/api/admin/players/cccccccc-cccc-4ccc-8ccc-cccccccccccc/metadata";
  const denied = await request.patch(`http://127.0.0.1:4117${path}`, { headers: { Authorization: `Bearer ${visitor}` }, data: { expectedName: "Visitor", metadata: { name: "Changed by visitor" } } });
  expect(denied.status()).toBe(403);
  const admin = await signIn(page, request, "simply"); await page.reload();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  // Keep the content editor mounted to exercise both independent exit guards.
  await nav.getByRole("button", { name: "Content", exact: true }).click();
  await expect(page.getByLabel("Search campaigns")).toBeVisible();
  await nav.getByRole("button", { name: "Players", exact: true }).click();
  await page.getByRole("button", { name: "View player Visitor", exact: true }).click();
  const profile = page.getByRole("region", { name: "Selected player" });
  await profile.getByRole("button", { name: "Edit metadata" }).click();
  await expect(page.getByLabel("Player name", { exact: true })).toBeFocused();
  await page.getByLabel("Player name", { exact: true }).fill("Visitor Updated");
  page.once("dialog", (dialog) => dialog.dismiss());
  await nav.getByRole("button", { name: "Matches", exact: true }).click();
  await expect(page.getByLabel("Player name", { exact: true })).toHaveValue("Visitor Updated");
  await page.route(`**${path}`, (route) => route.fulfill({ status: 409, contentType: "application/json", body: JSON.stringify({ error: "This player's name changed elsewhere. Refresh the profile before saving again." }) }));
  await profile.getByRole("button", { name: "Save metadata" }).click();
  await expect(profile.getByRole("alert")).toContainText("changed elsewhere");
  await expect(page.getByLabel("Player name", { exact: true })).toHaveValue("Visitor Updated");
  await page.unroute(`**${path}`);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "artifacts/admin-players-edit-mobile.png", fullPage: true });
  expect((await new AxeBuilder({ page }).include(".gauntlet-admin").analyze()).violations).toEqual([]);
  await profile.getByRole("button", { name: "Save metadata" }).click();
  await expect(profile.getByRole("heading", { name: "Visitor Updated" })).toBeVisible();
  await expect(page.getByRole("status")).toHaveText("Player metadata saved.");
  await page.reload();
  await nav.getByRole("button", { name: "Players", exact: true }).click();
  await expect(page.getByRole("button", { name: "View player Visitor Updated", exact: true })).toBeVisible();
  const restored = await request.patch(`http://127.0.0.1:4117${path}`, { headers: { Authorization: `Bearer ${admin}` }, data: { expectedName: "Visitor Updated", metadata: { name: "Visitor" } } });
  expect(restored.ok()).toBeTruthy();
});

test("operator edits, validates, previews, publishes and restores a shared content release", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: `Bearer ${token}` };
  const live = async () => (await (await request.get("http://127.0.0.1:4117/api/game-content", { maxRetries: 2 })).json()).content;
  const original = await live();
  const historyBefore = await (await request.get("http://127.0.0.1:4117/api/admin/matches", { headers })).json();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect The Jewel of Rumie", exact: true }).click();
  await page.getByLabel("Draft campaign introduction").fill("A saved draft introduction for browser verification.");
  await page.getByRole("button", { name: "Save campaign introduction to draft" }).click();
  await expect(page.getByText("1 saved field change", { exact: true })).toBeVisible();
  expect((await live()).campaigns.rumin.pitch).toBe(original.campaigns.rumin.pitch);
  await page.getByRole("button", { name: /^Cards \d+\b/ }).click();
  await page.getByLabel("Search cards").fill("Capital Investment Spear");
  await page.getByRole("button", { name: "Inspect Capital Investment Spear", exact: true }).click();
  await page.getByLabel("Draft name", { exact: true }).fill("Capital Investment Spear · review");
  await page.getByRole("button", { name: "Save name to draft", exact: true }).click();
  await expect(page.getByText("2 saved field changes", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: /^Encounters 56/ }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny", exact: true }).click();
  await page.getByLabel("Draft title", { exact: true }).fill("Brothers of Destiny · preview");
  await page.getByRole("button", { name: "Save title to draft", exact: true }).click();
  await expect(page.getByText("3 saved field changes", { exact: true })).toBeVisible();
  await nav.getByText("Game", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect Practice privately", exact: true }).click();
  await page.getByLabel("Draft mode description").fill("Practice with a reviewed content release.");
  await page.getByRole("button", { name: "Save mode description to draft" }).click();
  await expect(page.getByText("4 saved field changes", { exact: true })).toBeVisible();
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny · preview", exact: true }).click();
  await page.getByRole("button", { name: "Validate draft", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Draft validation completed.");
  await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
  const preview = page.getByRole("region", { name: "Isolated draft preview" });
  await page.getByText("Open presentation preview", { exact: true }).click();
  await expect(preview.getByRole("heading", { name: "Brothers of Destiny · preview", exact: true })).toBeVisible();
  await expect(preview.getByRole("button", { name: "Begin Battle", exact: true })).toBeDisabled();
  await preview.screenshot({ path: "artifacts/admin-authoring-preview.png" });
  expect((await live()).contentVersion).toBe(original.contentVersion);
  await nav.getByText("Publishing", { exact: true }).click();
  await page.getByLabel("Release name").fill("Browser reviewed release");
  await page.getByRole("button", { name: "Publish release", exact: true }).click();
  await page.getByRole("button", { name: "Confirm publish", exact: true }).click();
  await expect(page.getByText("Live content · no draft", { exact: true })).toBeVisible();
  const published = await live();
  expect(published.contentVersion).not.toBe(original.contentVersion);
  expect(published.campaigns.rumin.chapters[0].title).toBe("Brothers of Destiny · preview");
  expect(published.modeMetadata.practice.description).toBe("Practice with a reviewed content release.");
  await page.screenshot({ path: "artifacts/admin-publication-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Restore Deployed source baseline", exact: true }).click();
  await page.getByRole("button", { name: "Confirm rollback", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Previous release restored for future games.");
  expect((await live()).contentVersion).toBe(original.contentVersion);
  const historyAfter = await (await request.get("http://127.0.0.1:4117/api/admin/matches", { headers })).json();
  expect(historyAfter).toEqual(historyBefore);
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: /^Factions 11/ }).click();
  await page.getByRole("button", { name: "Inspect Rumin", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  const accessibility = await new AxeBuilder({ page }).include(".gauntlet-admin").analyze();
  expect(accessibility.violations).toEqual([]);
  await page.screenshot({ path: "artifacts/admin-authoring-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("typed mechanics can be edited, playtested in the real engine, published and rolled back", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: `Bearer ${token}` };
  const before = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: /^Encounters 56/ }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny", exact: true }).click();
  await page.getByLabel("Boss Life", { exact: true }).fill("31");
  await page.getByRole("button", { name: "Save encounter mechanics to draft", exact: true }).click();
  await expect(page.getByText("1 saved field change", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
  await page.getByRole("button", { name: "Start Brothers of Destiny playtest", exact: true }).click();
  const playtest = page.getByRole("region", { name: "Real engine playtest" });
  await expect(playtest.locator(".admin-facts").getByText("31", { exact: true })).toBeVisible();
  const action = playtest.getByRole("button", { name: "Pass priority", exact: true });
  await action.click();
  await expect(playtest.getByText(/Engine action checked for this saved draft/)).toBeVisible();
  const a11y = await new AxeBuilder({ page }).include(".workshop-editor").analyze();
  expect(a11y.violations).toEqual([]);
  await page.screenshot({ path: "artifacts/admin-v2-mechanical-playtest.png", fullPage: true });
  await nav.getByText("Publishing", { exact: true }).click();
  await page.getByLabel("Release name").fill("Browser mechanical release");
  await page.getByRole("button", { name: "Publish release", exact: true }).click();
  await page.getByRole("button", { name: "Confirm publish", exact: true }).click();
  await expect(page.getByText("Live content · no draft", { exact: true })).toBeVisible();
  const content = await (await request.get("http://127.0.0.1:4117/api/game-content", { maxRetries: 2 })).json();
  expect(content.content.campaigns.rumin.chapters[0].setup.bossLife).toBe(31);
  await page.getByRole("button", { name: "Restore Deployed source baseline", exact: true }).click();
  await page.getByRole("button", { name: "Confirm rollback", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Previous release restored for future games.");
  const after = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  expect(after.activeReleaseId).toBe(before.activeReleaseId);
});

test("manifest-picked faction and portrait artwork previews load immutable draft assets", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: "Bearer " + token };
  const original = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  const artwork = original.assetLibrary.find((entry) => entry.source === "/assets/gauntlet/sheen-card.webp");
  expect(artwork).toBeTruthy();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  const role = original.live.domains.characters.find((entry) => entry.factionId === "rumin" && entry.role === "commander");
  for (const [tab, name, field] of [[/^Factions 11/, "Rumin", "faction artwork"], [new RegExp("^Characters / opponents"), role.name, "portrait"]]) {
    await page.getByRole("button", { name: tab }).click();
    await page.getByRole("button", { name: "Inspect " + name, exact: true }).click();
    await page.getByLabel("Draft " + field, { exact: true }).fill(artwork.id);
    await page.getByRole("button", { name: "Save " + field + " to draft", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Field saved to the shared draft. Live content is unchanged.");
    await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
    const preview = page.getByRole("region", { name: "Isolated draft preview" });
    const image = preview.getByRole("img", { name, exact: true });
    await expect(image).toHaveAttribute("src", artwork.path);
    await expect.poll(() => image.evaluate((element) => element.complete && element.naturalWidth > 0)).toBeTruthy();
    await preview.screenshot({ path: "artifacts/admin-qualification-" + field.replace(/ /g, "-") + ".png" });
  }
  const current = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  expect(current.activeReleaseId).toBe(original.activeReleaseId);
  expect((await request.post("http://127.0.0.1:4117/api/admin/authoring/discard", { headers, data: { expectedRevision: current.revision } })).ok()).toBeTruthy();
});

test("Admin is discoverable only after access approval and review controls retain keyboard context", async ({ page, request }) => {
  await page.goto("/");
  const adminLink = page.getByRole("button", { name: /^Admin Content and operations/ });
  await expect(adminLink).toHaveCount(0);
  await signIn(page, request, "Visitor"); await page.reload();
  await expect(page.getByRole("heading", { name: "Journey", exact: true })).toBeVisible();
  await expect(adminLink).toHaveCount(0);
  await signIn(page, request, "simply"); await page.reload();
  await expect(adminLink).toBeVisible();
  await page.getByRole("navigation", { name: "Gauntlet areas" }).screenshot({ path: "artifacts/admin-ux-navigation.png" });
  await adminLink.click();
  await page.getByRole("button", { name: "Close admin", exact: true }).click();
  await expect(adminLink).toBeVisible();
  await adminLink.click();
  await page.getByRole("button", { name: "56 Encounters", exact: true }).click();
  await expect(page.getByRole("button", { name: /^Encounters 56/ })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "Validate draft", exact: true })).toBeDisabled();
  await page.getByLabel("Search encounters").fill("nothing matches this encounter");
  await expect(page.getByRole("status")).toContainText("No encounters match this search");
  await page.getByLabel("Search encounters").fill("Verdant");
  await page.getByRole("button", { name: "Inspect The Verdant Uprising", exact: true }).click();
  await expect(page.getByLabel("Test faction", { exact: true })).toHaveValue("sheen");
  await expect(page.getByLabel("Test faction", { exact: true })).toBeDisabled();
  await page.getByRole("region", { name: "Real engine playtest" }).screenshot({ path: "artifacts/admin-ux-playtest.png" });
  await page.getByLabel("Draft title", { exact: true }).fill("The Verdant Uprising · UX review");
  await page.getByRole("button", { name: "Save title to draft", exact: true }).click();
  await expect(page.getByText("1 saved field change", { exact: true })).toBeVisible();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByRole("button", { name: "Publishing", exact: true }).click();
  const discard = page.getByRole("button", { name: "Discard shared draft", exact: true });
  await discard.focus();
  await page.keyboard.press("Enter");
  const confirmation = page.getByRole("region", { name: "Confirm content operation" });
  await expect(confirmation).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Confirm discard", exact: true })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(confirmation.getByRole("button", { name: "Cancel", exact: true })).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(discard).toBeFocused();
  await page.keyboard.press("Enter");
  await confirmation.screenshot({ path: "artifacts/admin-ux-confirmation.png" });
  await page.getByRole("button", { name: "Confirm discard", exact: true }).click();
  await expect(page.getByText("Live content · no draft", { exact: true })).toBeVisible();
  await nav.getByRole("button", { name: "Players", exact: true }).click();
  await page.getByLabel("Filter this page").fill("not a registered name");
  await expect(page.getByRole("status")).toContainText("No players match this filter on the loaded page");
  await page.getByRole("button", { name: "Back to Gauntlet", exact: true }).click();
  await page.getByRole("button", { name: /^Identity Profile/ }).click();
  await page.getByRole("button", { name: "Sign Out", exact: true }).click();
  await expect(adminLink).toHaveCount(0);
});

test("disconnected authoring explains the blocker and preserves readable technical details on mobile", async ({ page, request }) => {
  // Explicitly simulated outage: production remains untouched.
  await page.route("**/api/admin/authoring", async (route) => {
    const response = await route.fetch();
    const body = await response.json();
    await route.fulfill({ response, json: { ...body, writable: false, connectionRequired: true } });
  });
  await page.goto("/admin/gauntlet");
  await signIn(page, request, "simply"); await page.reload();
  await page.getByRole("button", { name: /^\d+ Cards$/ }).click();
  await expect(page.getByRole("alert")).toContainText("Browsing live content");
  await expect(page.getByRole("button", { name: "Validate draft", exact: true })).toBeDisabled();
  await page.getByLabel("Search cards").fill("Capital Investment Spear");
  await page.getByRole("button", { name: "Inspect Capital Investment Spear", exact: true }).click();
  await expect(page.getByLabel("Draft name", { exact: true })).toBeDisabled();
  await page.screenshot({ path: "artifacts/admin-ux-disconnected-desktop.png" });
  await page.getByText("Connection setup details", { exact: true }).click();
  await expect(page.getByText(/The backend needs GAUNTLET_GITHUB_TOKEN/)).toBeVisible();
  await page.getByText("Advanced / Technical · identity and source", { exact: true }).click();
  await expect(page.getByLabel("Selected content").getByText(/Source boundary:/)).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect((await new AxeBuilder({ page }).include(".gauntlet-admin").analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole("heading", { name: "Gauntlet Admin", exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: "artifacts/admin-ux-disconnected-mobile.png" });
});

test("Encounter Workshop keeps editing and engine evidence tied to the correct saved draft", async ({ page, request }) => {
  test.setTimeout(180000);
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: `Bearer ${token}` }, base = "http://127.0.0.1:4117/api/admin/authoring";
  const saved = async () => (await request.get(base, { headers })).json();
  const initial = await saved();
  await page.getByRole("button", { name: "56 Encounters", exact: true }).click();
  await page.getByLabel("Search encounters").fill("Brothers");
  await page.getByRole("button", { name: "Inspect Brothers of Destiny", exact: true }).click();
  const story = page.getByLabel("Draft story", { exact: true });
  await story.fill("Workshop acceptance story.");
  for (const name of ["Back to Gauntlet", "Close admin", "Refresh admin", "Review release"]) {
    page.once("dialog", (dialog) => dialog.dismiss());
    await page.getByRole("button", { name, exact: true }).click();
    await expect(story).toHaveValue("Workshop acceptance story.");
  }
  page.once("dialog", (dialog) => dialog.dismiss());
  await page.getByRole("button", { name: /^Cards \d+\b/ }).click();
  await expect(story).toHaveValue("Workshop acceptance story.");
  // Browser refresh/close has the native unload guard, without navigating away.
  expect(await page.evaluate(() => !window.dispatchEvent(new Event("beforeunload", { cancelable: true })))).toBeTruthy();
  await page.getByRole("button", { name: "Save story to draft", exact: true }).click();
  await expect(page.getByText("1 saved field change", { exact: true })).toBeVisible();
  await page.getByLabel("Boss Life", { exact: true }).fill("101");
  await page.getByRole("button", { name: "Save encounter mechanics to draft", exact: true }).click();
  expect(await page.getByLabel("Boss Life", { exact: true }).evaluate((input) => input.validity.rangeOverflow)).toBeTruthy();
  expect((await saved()).changes.length).toBe(1);
  await page.getByLabel("Boss Life", { exact: true }).fill("30");
  await page.getByLabel("Boss Ability Id", { exact: true }).selectOption("even-feint");
  await page.getByLabel("Boss Ability Even Bonus", { exact: true }).fill("2");
  await page.getByRole("button", { name: "Save encounter mechanics to draft", exact: true }).click();
  await expect(page.getByText("2 saved field changes", { exact: true })).toBeVisible();
  const artwork = initial.assetLibrary.find((entry) => entry.source === "/assets/gauntlet/sheen-card.webp");
  await page.getByLabel("Draft scene artwork", { exact: true }).fill(artwork.id);
  await page.getByRole("button", { name: "Save scene artwork to draft", exact: true }).click();
  await expect(page.getByText("3 saved field changes", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Validate draft", exact: true }).click();
  await expect(page.getByText("Draft validation completed.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
  await page.getByText("Open presentation preview", { exact: true }).click();
  await expect(page.getByRole("region", { name: "Isolated draft preview" }).getByRole("heading", { name: "Brothers of Destiny", exact: true })).toBeVisible();
  await page.getByText("Open presentation preview", { exact: true }).click();
  await page.locator("#workshop-context").evaluate((element) => element.scrollIntoView({ block: "start" }));
  await page.screenshot({ path: "artifacts/workshop-desktop-editor.png" });
  const playtest = page.getByRole("region", { name: "Real engine playtest" });
  let pending = page.waitForResponse((response) => response.url().endsWith("/authoring/playtest") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Start Brothers of Destiny playtest", exact: true }).click();
  let session = (await (await pending).json()).playtest;
  expect(session.context.encounterId).toBe("brothers-of-destiny");
  expect(session.context.chapter).toBe(1);
  expect(session.draftHash).toBe((await saved()).draft.hash);
  await expect(playtest.getByText("Current saved draft · at last refresh", { exact: true })).toBeVisible();
  await playtest.scrollIntoViewIfNeeded();
  await page.screenshot({ path: "artifacts/workshop-active-playtest.png" });
  let attacked = false;
  for (let step = 0; step < 35 && (session.game.turn < 2 || !session.evidence.events.some((event) => event.type === "damage.calculated")); step++) {
    const game = session.game;
    const actor = game.phase === "end" ? game.endPlacementStep === 0 ? game.endPlacementFirstPlayer : 3 - game.endPlacementFirstPlayer : game.priority;
    const automated = actor === 2;
    const action = session.actions.find((action) => action.command.type === "declineBlock")
      || (!attacked && session.actions.find((action) => action.command.type === "declareHandAttack"))
      || session.actions.find((action) => ["passPriority", "skipPlacement"].includes(action.command.type));
    if (!automated && action?.command.type === "declareHandAttack") attacked = true;
    pending = page.waitForResponse((response) => response.url().endsWith("/playtest/command"));
    await playtest.getByRole("button", { name: automated ? "Run opponent action" : action.label, exact: true }).click();
    const response = await pending;
    expect(response.ok()).toBeTruthy();
    session = (await response.json()).playtest;
    if (step === 1) {
      await playtest.getByRole("status").evaluate((element) => element.scrollIntoView({ block: "start" }));
      await page.screenshot({ path: "artifacts/workshop-active-playtest.png" });
    }
  }
  expect(session.game.turn).toBeGreaterThanOrEqual(2);
  expect(session.evidence.events.some((event) => event.type === "damage.calculated")).toBeTruthy();
  await expect(playtest.getByText(/Engine action checked for this saved draft/)).toBeVisible();
  pending = page.waitForResponse((response) => response.url().endsWith("/playtest/command"));
  await playtest.getByRole("button", { name: "Concede", exact: true }).click();
  session = (await (await pending).json()).playtest;
  expect(session.evidence.status).toBe("Conceded");
  await playtest.getByRole("heading", { name: /Conceded/ }).evaluate((element) => element.scrollIntoView({ block: "start" }));
  await page.screenshot({ path: "artifacts/workshop-post-test.png" });
  // Links open actual definitions and keep a route back to this same encounter/session.
  await playtest.getByRole("button", { name: "Rumin", exact: true }).click();
  await expect(page.getByRole("region", { name: "Selected content" })).toContainText("Rumin");
  await page.getByRole("button", { name: "Return to Brothers of Destiny · Encounter Workshop", exact: true }).click();
  await expect(playtest.getByRole("heading", { name: /Conceded/ })).toBeVisible();
  await story.fill("Revised after the first engine session.");
  await page.getByRole("button", { name: "Save story to draft", exact: true }).click();
  await expect(playtest.getByText("Stale playtest · saved draft changed", { exact: true })).toBeVisible();
  await expect(page.getByText("Preview needed", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Validate draft", exact: true }).click();
  await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
  page.once("dialog", (dialog) => dialog.accept());
  pending = page.waitForResponse((response) => response.url().endsWith("/authoring/playtest"));
  await page.getByRole("button", { name: "Start Brothers of Destiny playtest", exact: true }).click();
  const replacement = (await (await pending).json()).playtest;
  expect(replacement.draftHash).not.toBe(session.draftHash);
  await expect(playtest.getByText("Current saved draft · at last refresh", { exact: true })).toBeVisible();
  pending = page.waitForResponse((response) => response.url().endsWith("/playtest/command"));
  await playtest.getByRole("button", { name: "Pass priority", exact: true }).click();
  expect((await pending).ok()).toBeTruthy();
  await page.getByRole("button", { name: "Review release", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Review draft changes", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Return to Brothers of Destiny · Encounter Workshop", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator("#workshop-context").evaluate((element) => element.scrollIntoView({ block: "start" }));
  await page.screenshot({ path: "artifacts/workshop-mobile-editor.png" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect((await new AxeBuilder({ page }).include(".encounter-workshop").analyze()).violations).toEqual([]);
  await page.getByText("Open presentation preview", { exact: true }).click();
  expect((await new AxeBuilder({ page }).include(".encounter-workshop").analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByText("Open presentation preview", { exact: true }).click();
  await page.getByRole("combobox", { name: "Jump to section", exact: true }).focus();
  await page.keyboard.press("ArrowDown");
  await expect(page.getByLabel("Draft title", { exact: true })).toBeFocused();
  await page.setViewportSize({ width: 1024, height: 600 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  // Simulated server expiration; actual TTL is covered by the server clock test.
  await page.route("**/playtest/command", (route) => route.fulfill({ status: 404, json: { error: "Playtest expired or is not yours. Start a new playtest." } }));
  await playtest.getByRole("button", { name: "Pass priority", exact: true }).click();
  await expect(playtest.getByText("Expired session · start again", { exact: true })).toBeVisible();
  await expect(playtest.getByRole("button", { name: "Run opponent action", exact: true })).toBeDisabled();
  const final = await saved();
  expect(final.activeReleaseId).toBe(initial.activeReleaseId);
  expect((await request.post(`${base}/discard`, { headers, data: { expectedRevision: final.revision } })).ok()).toBeTruthy();
});

test("a second operator's revision conflict preserves local typing and requires an explicit retry", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: `Bearer ${token}` }, base = "http://127.0.0.1:4117/api/admin/authoring";
  await page.getByRole("button", { name: "56 Encounters", exact: true }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny", exact: true }).click();
  await page.getByLabel("Draft story", { exact: true }).fill("Local operator story.");
  const login = await (await request.post("http://127.0.0.1:4117/api/auth/login", { data: { name: "Burnt Ramen", password: "test-password" } })).json();
  const before = await (await request.get(base, { headers })).json();
  expect((await request.patch(`${base}/draft`, { headers: { Authorization: `Bearer ${login.token}` }, data: { expectedRevision: before.revision, domain: "encounters", id: "brothers-of-destiny", field: "story", value: "Other operator story." } })).ok()).toBeTruthy();
  await page.getByRole("button", { name: "Save story to draft", exact: true }).click();
  await expect(page.getByLabel("Draft story", { exact: true })).toHaveValue("Local operator story.");
  await expect(page.getByText(/The shared draft changed. Your local values were kept/)).toBeVisible();
  const changed = await (await request.get(base, { headers })).json();
  expect(changed.draft.snapshot.domains.encounters.find((row) => row.id === "brothers-of-destiny").story).toBe("Other operator story.");
  await page.locator("#admin-field-story").getByText("Saved shared draft value", { exact: true }).click();
  await expect(page.locator("#admin-field-story").getByText("Other operator story.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Use latest revision for retry", exact: true }).click();
  await page.getByRole("button", { name: "Save story to draft", exact: true }).click();
  await expect(page.getByText("Field saved to the shared draft. Live content is unchanged.", { exact: true })).toBeVisible();
  const final = await (await request.get(base, { headers })).json();
  expect(final.draft.snapshot.domains.encounters.find((row) => row.id === "brothers-of-destiny").story).toBe("Local operator story.");
  await request.post(`${base}/discard`, { headers, data: { expectedRevision: final.revision } });
});
