const { test, expect } = require("@playwright/test");
const AxeBuilder = require("@axe-core/playwright").default;

async function signIn(page, request, name) {
  const response = await request.post("http://127.0.0.1:4117/api/auth/login", { data: { name, password: "test-password" } });
  expect(response.ok()).toBeTruthy();
  const { token } = await response.json();
  await page.evaluate((value) => localStorage.setItem("gauntlet_auth_token", value), token);
  return token;
}

test("both authorized accounts can inspect every section; other accounts and guests cannot", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  await expect(page.getByRole("heading", { name: "Private administration" })).toBeVisible();
  expect((await request.get("http://127.0.0.1:4117/admin/gauntlet/content")).status()).toBe(401);
  await page.getByRole("button", { name: "Sign in through Identity" }).click();
  await page.getByPlaceholder("Account name", { exact: true }).fill("simply");
  await page.getByPlaceholder("Password", { exact: true }).fill("test-password");
  await page.getByRole("button", { name: "Sign In", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Gauntlet Admin", exact: true })).toBeVisible();
  const visitor = await signIn(page, request, "Visitor");
  await page.reload();
  await expect(page.getByRole("alert")).toContainText("does not have access");
  expect((await request.get("http://127.0.0.1:4117/api/admin/catalog", { headers: { Authorization: `Bearer ${visitor}` } })).status()).toBe(403);

  await signIn(page, request, "simply");
  await page.reload();
  await expect(page.getByRole("heading", { name: "Gauntlet Admin", exact: true })).toBeVisible();
  await expect(page.locator(".admin-facts").getByText(/^gauntlet-content-[a-f0-9]{64}$/)).toBeVisible();
  await page.screenshot({ path: "artifacts/admin-overview-desktop.png", fullPage: true });
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: /^Cards 126/ }).click();
  await page.getByLabel("Search cards").fill("Capital Investment Spear");
  await page.getByRole("button", { name: "Inspect Capital Investment Spear", exact: true }).click();
  await expect(page.getByLabel("Selected content")).toContainText("server/gameContent.js");
  await page.screenshot({ path: "artifacts/admin-content-desktop.png", fullPage: true });
  await nav.getByText("Game", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Starting state" })).toBeVisible();
  await nav.getByText("Players", { exact: true }).click();
  await page.locator(".admin-player summary").filter({ hasText: "simply" }).click();
  await expect(page.locator(".admin-player[open]").getByText("Canonical match references")).toBeVisible();
  await nav.getByText("Matches", { exact: true }).click();
  await page.getByRole("button", { name: /^Inspect match/ }).click();
  await expect(page.getByRole("heading", { name: /Authoritative audit history/ })).toBeVisible();
  await nav.getByText("Publishing", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Release history and rollback" })).toBeVisible();
  await nav.getByText("System", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Schema and rules versions" })).toBeVisible();
  const accessibility = await new AxeBuilder({ page }).include(".gauntlet-admin").analyze();
  expect(accessibility.violations).toEqual([]);

  await signIn(page, request, "Burnt Ramen");
  await page.reload();
  await expect(page.getByRole("heading", { name: "Gauntlet Admin", exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(nav.getByText("System", { exact: true })).toBeVisible();
  await page.screenshot({ path: "artifacts/admin-overview-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("operator edits, validates, previews, publishes and restores a shared content release", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: `Bearer ${token}` };
  const live = async () => (await (await request.get("http://127.0.0.1:4117/api/game-content", { maxRetries: 2 })).json()).content;
  const original = await live();
  const historyBefore = await (await request.get("http://127.0.0.1:4117/api/admin/matches", { headers })).json();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect The Jewel of Rumie", exact: true }).click();
  await page.getByLabel("Draft campaign introduction").fill("A saved draft introduction for browser verification.");
  await page.getByRole("button", { name: "Save campaign introduction to draft" }).click();
  await expect(page.getByText("1 saved field change", { exact: true })).toBeVisible();
  expect((await live()).campaigns.rumin.pitch).toBe(original.campaigns.rumin.pitch);
  await page.getByRole("button", { name: /^Cards 126/ }).click();
  await page.getByLabel("Search cards").fill("Capital Investment Spear");
  await page.getByRole("button", { name: "Inspect Capital Investment Spear", exact: true }).click();
  await page.getByLabel("Draft name", { exact: true }).fill("Capital Investment Spear · review");
  await page.getByRole("button", { name: "Save name to draft", exact: true }).click();
  await expect(page.getByText("2 saved field changes", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: /^Encounters 56/ }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny", exact: true }).click();
  await page.getByLabel("Draft title", { exact: true }).fill("Brothers of Destiny · preview");
  await page.getByRole("button", { name: "Save title to draft", exact: true }).click();
  await expect(page.getByText("3 saved field changes", { exact: true })).toBeVisible();
  await nav.getByText("Game", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect Practice privately", exact: true }).click();
  await page.getByLabel("Draft mode description").fill("Practice with a reviewed content release.");
  await page.getByRole("button", { name: "Save mode description to draft" }).click();
  await expect(page.getByText("4 saved field changes", { exact: true })).toBeVisible();
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny · preview", exact: true }).click();
  await page.getByRole("button", { name: "Validate draft", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Draft validation completed.");
  await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
  const preview = page.getByRole("region", { name: "Isolated draft preview" });
  await expect(preview.getByRole("heading", { name: "Brothers of Destiny · preview", exact: true })).toBeVisible();
  await expect(preview.getByRole("button", { name: "Begin Battle", exact: true })).toBeDisabled();
  await preview.screenshot({ path: "artifacts/admin-authoring-preview.png" });
  expect((await live()).contentVersion).toBe(original.contentVersion);
  await nav.getByText("Publishing", { exact: true }).click();
  await page.getByLabel("Release name").fill("Browser reviewed release");
  await page.getByRole("button", { name: "Publish release", exact: true }).click();
  await page.getByRole("button", { name: "Confirm publish", exact: true }).click();
  await expect(page.getByText("Live content · no draft", { exact: true })).toBeVisible();
  const published = await live();
  expect(published.contentVersion).not.toBe(original.contentVersion);
  expect(published.campaigns.rumin.chapters[0].title).toBe("Brothers of Destiny · preview");
  expect(published.modeMetadata.practice.description).toBe("Practice with a reviewed content release.");
  await page.screenshot({ path: "artifacts/admin-publication-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Restore Deployed source baseline", exact: true }).click();
  await page.getByRole("button", { name: "Confirm rollback", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Previous release restored for future games.");
  expect((await live()).contentVersion).toBe(original.contentVersion);
  const historyAfter = await (await request.get("http://127.0.0.1:4117/api/admin/matches", { headers })).json();
  expect(historyAfter).toEqual(historyBefore);
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: /^Factions 11/ }).click();
  await page.getByRole("button", { name: "Inspect Rumin", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  const accessibility = await new AxeBuilder({ page }).include(".gauntlet-admin").analyze();
  expect(accessibility.violations).toEqual([]);
  await page.screenshot({ path: "artifacts/admin-authoring-mobile.png", fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});

test("typed mechanics can be edited, playtested in the real engine, published and rolled back", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: `Bearer ${token}` };
  const before = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  await page.getByRole("button", { name: /^Encounters 56/ }).click();
  await page.getByRole("button", { name: "Inspect Brothers of Destiny", exact: true }).click();
  await page.getByLabel("Boss Life", { exact: true }).fill("31");
  await page.getByRole("button", { name: "Save encounter mechanics to draft", exact: true }).click();
  await expect(page.getByText("1 saved field change", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
  await page.getByRole("button", { name: "Start Brothers of Destiny playtest", exact: true }).click();
  const playtest = page.getByRole("region", { name: "Real engine playtest" });
  await expect(playtest.getByRole("heading", { name: /Remex · 31 life/ })).toBeVisible();
  const action = playtest.getByRole("button", { name: "Pass priority", exact: true });
  await action.click();
  await expect(playtest.getByText("The current saved draft has a recorded engine playtest.", { exact: true })).toBeVisible();
  const a11y = await new AxeBuilder({ page }).include(".admin-editor").analyze();
  expect(a11y.violations).toEqual([]);
  await page.screenshot({ path: "artifacts/admin-v2-mechanical-playtest.png", fullPage: true });
  await nav.getByText("Publishing", { exact: true }).click();
  await page.getByLabel("Release name").fill("Browser mechanical release");
  await page.getByRole("button", { name: "Publish release", exact: true }).click();
  await page.getByRole("button", { name: "Confirm publish", exact: true }).click();
  await expect(page.getByText("Live content · no draft", { exact: true })).toBeVisible();
  const content = await (await request.get("http://127.0.0.1:4117/api/game-content", { maxRetries: 2 })).json();
  expect(content.content.campaigns.rumin.chapters[0].setup.bossLife).toBe(31);
  await page.getByRole("button", { name: "Restore Deployed source baseline", exact: true }).click();
  await page.getByRole("button", { name: "Confirm rollback", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Previous release restored for future games.");
  const after = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  expect(after.activeReleaseId).toBe(before.activeReleaseId);
});

test("manifest-picked faction and portrait artwork previews load immutable draft assets", async ({ page, request }) => {
  await page.goto("/admin/gauntlet");
  const token = await signIn(page, request, "simply"); await page.reload();
  const headers = { Authorization: "Bearer " + token };
  const original = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  const artwork = original.assetLibrary.find((entry) => entry.source === "/assets/gauntlet/sheen-card.webp");
  expect(artwork).toBeTruthy();
  const nav = page.getByRole("navigation", { name: "Administration sections" });
  await nav.getByText("Content", { exact: true }).click();
  const role = original.live.domains.characters.find((entry) => entry.factionId === "rumin" && entry.role === "commander");
  for (const [tab, name, field] of [[/^Factions 11/, "Rumin", "faction artwork"], [new RegExp("^Characters / opponents"), role.name, "portrait"]]) {
    await page.getByRole("button", { name: tab }).click();
    await page.getByRole("button", { name: "Inspect " + name, exact: true }).click();
    await page.getByLabel("Draft " + field, { exact: true }).fill(artwork.id);
    await page.getByRole("button", { name: "Save " + field + " to draft", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText("Field saved to the shared draft. Live content is unchanged.");
    await page.getByRole("button", { name: "Preview saved draft", exact: true }).click();
    const preview = page.getByRole("region", { name: "Isolated draft preview" });
    const image = preview.getByRole("img", { name, exact: true });
    await expect(image).toHaveAttribute("src", artwork.path);
    await expect.poll(() => image.evaluate((element) => element.complete && element.naturalWidth > 0)).toBeTruthy();
    await preview.screenshot({ path: "artifacts/admin-qualification-" + field.replace(/ /g, "-") + ".png" });
  }
  const current = await (await request.get("http://127.0.0.1:4117/api/admin/authoring", { headers })).json();
  expect(current.activeReleaseId).toBe(original.activeReleaseId);
  expect((await request.post("http://127.0.0.1:4117/api/admin/authoring/discard", { headers, data: { expectedRevision: current.revision } })).ok()).toBeTruthy();
});
