const { test, expect } = require("@playwright/test");
const fs = require("node:fs");
const path = require("node:path");
const { COLLECTION_CARDS } = require("../server/gameContent");

test("full-art catalog and responsive workshop preserve selected suits and saved replacements", async ({ page, request, baseURL }) => {
  test.setTimeout(120000);
  const name = `Card QA ${Date.now()}`;
  const response = await request.post("http://127.0.0.1:4102/api/auth/register", { data: { name, password: "Local-Card-Review-42" } });
  expect(response.ok()).toBeTruthy();
  const session = await response.json();
  const storePath = path.resolve(__dirname, "../.playwright-data/card-design-review/accounts.json");
  const store = JSON.parse(fs.readFileSync(storePath, "utf8"));
  const account = store.accounts.find((entry) => entry.id === session.account.id);
  account.stats.collection.gameplayEntitlements = Object.fromEntries(COLLECTION_CARDS.map((card) => [card.id, 4]));
  fs.writeFileSync(storePath, JSON.stringify(store, null, 2));
  const brokenFaces = [];
  page.on("response", (entry) => { if (entry.url().includes("/constructed/") && entry.status() >= 400) brokenFaces.push(entry.url()); });
  await page.addInitScript((token) => localStorage.setItem("gauntlet_auth_token", token), session.token);
  await page.goto(baseURL);
  await page.locator('button[data-area="build"]').click();
  await page.getByRole("button", { name: "Open Collection Workshop" }).click();
  await page.getByRole("tab", { name: "Catalog", exact: true }).click();
  await expect(page.locator(".catalog-card-tile .custom-playing-card-face")).toHaveCount(72);
  await expect.poll(() => page.locator(".catalog-card-tile img").evaluateAll((images) => images.every((img) => img.complete && img.naturalWidth === 500))).toBe(true);
  const catalogFaces = await page.locator(".catalog-card-tile > .special-card-presentation").evaluateAll((faces) => faces.map((face) => {
    const bounds = face.getBoundingClientRect();
    return { width: bounds.width, height: bounds.height };
  }));
  expect(catalogFaces.every(({ width, height }) => Math.abs(width / height - (5 / 7)) < 0.01)).toBe(true);
  expect(new Set(catalogFaces.map(({ width }) => Math.round(width))).size).toBe(1);
  expect(new Set(catalogFaces.map(({ height }) => Math.round(height))).size).toBe(1);
  await page.getByRole("tab", { name: "Decks", exact: true }).click();
  await page.getByLabel("Deck faction", { exact: true }).selectOption("sheen");
  const definition = COLLECTION_CARDS.find((entry) => entry.id === "sheen-raincall-mender");
  const rank = ({ 11: "J", 12: "Q", 13: "K", 14: "A" })[definition.value] || String(definition.value);
  await page.getByRole("button", { name: `${rank} of hearts — Standard playing card`, exact: true }).click();
  await page.getByRole("button", { name: `Swap ${rank} of hearts for Raincall Mender`, exact: true }).click();
  const preview = page.locator(".deck-inspection-rail");
  await expect(preview.locator(".deck-preview-copy")).toContainText("Clean block: Heal 1.");
  await preview.getByText("Full rules & keywords", { exact: true }).click();
  await expect(preview.locator(".card-rules-details")).toContainText("After this blocks, gain 1 life if you took no damage from that attack.");
  await expect(preview.getByRole("link", { name: "Read keyword guide" })).toHaveAttribute("href", "/card-keywords.html#sheen-raincall-mender");
  await expect(preview.locator(".deck-slot-preview img")).toHaveAttribute("src", /sheen-raincall-mender-hearts\.webp\?v=2$/);
  await page.getByLabel("Deck name", { exact: true }).fill("Full Art Sheen QA");
  await page.getByRole("button", { name: "Create Deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save New Version", exact: true })).toBeEnabled();
  const out = path.resolve(__dirname, "../docs/generated-assets/workshop-compact-review");
  fs.mkdirSync(out, { recursive: true });
  await page.locator(".constructed-workbench").screenshot({ path: path.join(out, "workshop-full-art-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Cards", exact: true }).click();
  await expect(page.locator(".deck-slot.is-replaced img")).toHaveAttribute("src", /sheen-raincall-mender-hearts\.webp\?v=2$/);
  const bounds = await page.locator(".deck-workshop").boundingBox();
  expect(bounds.width).toBeLessThanOrEqual(390);
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "workshop-full-art-mobile.png") });
  expect(brokenFaces).toEqual([]);
  const saved = JSON.parse(fs.readFileSync(storePath, "utf8")).accounts.find((entry) => entry.id === account.id);
  expect(saved.stats.savedConstructedDeck.cardSuitChoices["sheen-raincall-mender"]).toEqual(["hearts"]);
  await page.goto(`${baseURL}/card-keywords.html#sheen-nus-verdant-edict`);
  await expect(page.locator("#sheen-nus-verdant-edict .short")).toHaveText("Third block: +1 value.");
  await expect(page.locator("#charge")).toContainText("acceleration counters");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
