const { test, expect } = require("@playwright/test");
const fs = require("node:fs");
const path = require("node:path");
const { COLLECTION_CARDS } = require("../server/gameContent");

test("deck names can be typed during creation and renamed without creating card versions", async ({ page, request, baseURL }) => {
  const response = await request.post("http://127.0.0.1:4104/api/auth/register", { data: { name: "Name QA " + Date.now(), password: "Local-Naming-Review-42" } });
  expect(response.ok()).toBeTruthy();
  const session = await response.json();
  const storePath = path.resolve(__dirname, "../.playwright-data/slot-workshop/accounts.json");
  const store = JSON.parse(fs.readFileSync(storePath, "utf8"));
  store.accounts.find(entry => entry.id === session.account.id).stats.collection.gameplayEntitlements = Object.fromEntries(COLLECTION_CARDS.map(card => [card.id, 4]));
  fs.writeFileSync(storePath, JSON.stringify(store));
  const savedDeck = () => JSON.parse(fs.readFileSync(storePath, "utf8")).accounts.find(entry => entry.id === session.account.id).stats.deckLibrary.decks[0];
  await page.addInitScript(token => localStorage.setItem("gauntlet_auth_token", token), session.token);
  const openWorkshop = async () => {
    await page.goto(baseURL);
    await page.locator('button[data-area="build"]').click();
    await page.getByRole("button", { name: "Open Collection Workshop" }).click();
    await page.getByRole("tab", { name: "Decks", exact: true }).click();
  };
  const typeName = async (field, name) => {
    await field.click();
    await field.press("ControlOrMeta+A");
    await field.pressSequentially(name, { delay: 40 });
    await expect(field).toHaveValue(name);
    await field.press("Tab");
  };
  await openWorkshop();
  const name = page.getByRole("textbox", { name: "Deck name", exact: true });
  await typeName(name, "My First Deck");
  await page.getByRole("button", { name: "Create Deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save New Version", exact: true })).toBeEnabled();
  expect(savedDeck().name).toBe("My First Deck");
  const versionId = savedDeck().currentVersionId;
  const card = COLLECTION_CARDS.find(entry => entry.factionId === "rumin");
  const rank = ({ 11: "J", 12: "Q", 13: "K", 14: "A" })[card.value] || String(card.value);
  await page.getByRole("button", { name: rank + " of " + card.suit + " — Standard playing card", exact: true }).click();
  await page.getByRole("button", { name: "Swap " + rank + " of " + card.suit + " for " + card.name, exact: true }).click();
  await typeName(name, "The Copper Guard");
  await page.getByRole("button", { name: "Save name", exact: true }).click();
  await expect.poll(() => savedDeck().name).toBe("The Copper Guard");
  expect(savedDeck().currentVersionId).toBe(versionId);
  expect(savedDeck().versions).toHaveLength(1);
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(1);
  await openWorkshop();
  await expect(name).toHaveValue("The Copper Guard");
  await page.setViewportSize({ width: 390, height: 844 });
  const fieldBounds = await name.boundingBox();
  const gridBounds = await page.locator(".deck-slot-panel").boundingBox();
  expect(fieldBounds.y).toBeLessThan(gridBounds.y);
  await page.locator(".deck-library-drawer > summary").click();
  await page.getByRole("button", { name: "Rename", exact: true }).click();
  const rename = page.getByRole("textbox", { name: "New deck name", exact: true });
  await typeName(rename, "Pocket Guard");
  await page.locator(".deck-library-row").getByRole("button", { name: "Save name", exact: true }).click();
  await expect.poll(() => savedDeck().name).toBe("Pocket Guard");
  expect(savedDeck().currentVersionId).toBe(versionId);
  await openWorkshop();
  await expect(name).toHaveValue("Pocket Guard");
  await expect(page.getByLabel("Saved deck", { exact: true }).locator("option:checked")).toHaveText("Pocket Guard");
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.locator(".deck-workshop").screenshot({ path: ".eggs/evidence/deck-naming-mobile.png" });
});
