const { test, expect } = require("@playwright/test");
const fs = require("node:fs");
const path = require("node:path");
const { COLLECTION_CARDS } = require("../server/gameContent");

test("52-card workshop saves exact swaps and boxes; packs reveal sequentially on desktop and mobile", async ({ page, request, baseURL }) => {
  test.setTimeout(120000);
  const response = await request.post("http://127.0.0.1:4104/api/auth/register", { data: { name: `Slot QA ${Date.now()}`, password: "Local-Slot-Review-42" } });
  expect(response.ok()).toBeTruthy();
  const session = await response.json();
  const storePath = path.resolve(__dirname, "../.playwright-data/slot-workshop/accounts.json");
  const store = JSON.parse(fs.readFileSync(storePath, "utf8"));
  const account = store.accounts.find((entry) => entry.id === session.account.id);
  account.stats.collection.gameplayEntitlements = Object.fromEntries(COLLECTION_CARDS.map((card) => [card.id, 4]));
  account.stats.collection.packCredits = 3;
  fs.writeFileSync(storePath, JSON.stringify(store, null, 2));
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript((token) => localStorage.setItem("gauntlet_auth_token", token), session.token);
  await page.goto(baseURL);
  await page.locator('button[data-area="build"]').click();
  await page.getByRole("button", { name: "Open Collection Workshop" }).click();
  await page.getByRole("tab", { name: "Decks", exact: true }).click();
  await expect(page.locator(".deck-slot")).toHaveCount(52);
  await expect(page.locator(".deck-faction-picker button")).toHaveCount(8);
  await page.locator(".deck-faction-picker").getByRole("button", { name: /Sheen/ }).click();
  const card = COLLECTION_CARDS.find((entry) => entry.id === "sheen-raincall-mender");
  const rank = ({ 11: "J", 12: "Q", 13: "K", 14: "A" })[card.value] || String(card.value);
  await page.getByRole("button", { name: `${rank} of hearts — Standard playing card`, exact: true }).click();
  await page.getByRole("button", { name: `Swap ${rank} of hearts for Raincall Mender`, exact: true }).click();
  await expect(page.locator(".deck-slot-preview img")).toHaveAttribute("src", /sheen-raincall-mender-hearts\.webp\?v=2$/);
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(1);
  await expect(page.locator(".deck-preview-copy")).toContainText("Clean block: Heal 1.");
  await page.locator(".deck-inspection-rail").getByText("Full rules & keywords", { exact: true }).click();
  await expect(page.locator(".deck-inspection-rail .card-rules-details")).toContainText("After this blocks, gain 1 life");
  await expect(page.locator(".deck-inspection-rail").getByRole("link", { name: "Read keyword guide" })).toHaveAttribute("href", "/card-keywords.html#sheen-raincall-mender");
  await page.getByRole("button", { name: "Obsidian deck box", exact: true }).click();
  await page.getByLabel("Deck name", { exact: true }).fill("Sheen in Obsidian");
  await page.getByRole("button", { name: "Create Deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save New Version", exact: true })).toBeEnabled();
  const getSaved = () => JSON.parse(fs.readFileSync(storePath, "utf8")).accounts.find((entry) => entry.id === account.id).stats.savedConstructedDeck;
  expect(getSaved().cardSuitChoices[card.id]).toEqual(["hearts"]);
  expect(getSaved().deckBoxId).toBe("obsidian");
  await page.getByRole("button", { name: `${rank} of hearts — Raincall Mender`, exact: true }).click();
  const out = path.resolve(__dirname, "../docs/generated-assets/workshop-review");
  fs.mkdirSync(out, { recursive: true });
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "deck-workshop-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".deck-workshop")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "deck-workshop-mobile.png") });
  await page.getByRole("button", { name: `Restore standard ${rank}♥`, exact: true }).click();
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(0);
  await page.getByRole("button", { name: "Save New Version", exact: true }).click();
  await expect.poll(() => getSaved().replacementCount).toBe(0);
  await page.getByRole("button", { name: "New Constructed", exact: true }).click();
  await expect(page.getByRole("button", { name: "Create Deck", exact: true })).toBeEnabled();
  await expect(page.getByLabel("Deck name", { exact: true })).toHaveValue("Rumin Constructed Deck");
  await page.locator(".deck-faction-picker").getByRole("button", { name: /Mekan/ }).click();
  await page.getByLabel("Deck General", { exact: true }).selectOption("hui");
  await page.getByLabel("Deck name", { exact: true }).fill("Mekan Hui");
  await page.getByRole("button", { name: "Create Deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save New Version", exact: true })).toBeEnabled();
  expect(getSaved().generalId).toBe("hui");
  await page.getByRole("tab", { name: "Packs", exact: true }).click();
  await page.getByRole("radio", { name: /Theatrical/ }).check();
  await page.getByRole("button", { name: "Open Earned Pack", exact: true }).first().click();
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: "Pause", exact: true }).click();
  await expect(dialog.getByRole("status")).toHaveText(/Breaking the seal/);
  await dialog.getByRole("button", { name: "Next card", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("uncommon");
  await dialog.screenshot({ path: path.join(out, "pack-opening-mobile.png") });
  await page.setViewportSize({ width: 1366, height: 900 });
  await dialog.screenshot({ path: path.join(out, "pack-opening-desktop.png") });
  await dialog.getByRole("button", { name: "Reveal all", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".pack-opened-cards article")).toHaveCount(8);
  expect(errors).toEqual([]);
});
