const { test, expect } = require("@playwright/test");
const fs = require("node:fs");
const path = require("node:path");
const { COLLECTION_CARDS } = require("../server/gameContent");

test("52-card workshop saves exact swaps and boxes; packs reveal sequentially on desktop and mobile", async ({ page, request, baseURL }) => {
  test.setTimeout(120000);
  const response = await request.post("http://127.0.0.1:4104/api/auth/register", { data: { name: `Slot QA ${Date.now()}`, password: "Local-Slot-Review-42" } });
  expect(response.ok()).toBeTruthy();
  const session = await response.json();
  const storePath = path.resolve(__dirname, "../.playwright-data/slot-workshop/accounts.json");
  const store = JSON.parse(fs.readFileSync(storePath, "utf8"));
  const account = store.accounts.find((entry) => entry.id === session.account.id);
  account.stats.collection.gameplayEntitlements = Object.fromEntries(COLLECTION_CARDS.map((card) => [card.id, 4]));
  account.stats.collection.packCredits = 3;
  fs.writeFileSync(storePath, JSON.stringify(store, null, 2));
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript((token) => localStorage.setItem("gauntlet_auth_token", token), session.token);
  await page.goto(baseURL);
  await page.locator('button[data-area="build"]').click();
  await page.getByRole("button", { name: "Open Collection Workshop" }).click();
  await page.getByRole("tab", { name: "Decks", exact: true }).click();
  await expect(page.locator(".deck-slot")).toHaveCount(52);
  await expect(page.getByLabel("Deck faction", { exact: true }).locator("option")).toHaveCount(10);
  await expect(page.getByRole("button", { name: "Compact", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect((await page.locator(".deck-slot-panel").boundingBox()).height).toBeLessThan(550);
  await expect(page.locator(".deck-settings")).not.toHaveAttribute("open", "");
  await expect(page.locator(".deck-library-drawer")).not.toHaveAttribute("open", "");
  await page.getByLabel("Deck faction", { exact: true }).selectOption("sheen");
  const card = COLLECTION_CARDS.find((entry) => entry.id === "sheen-raincall-mender");
  const rank = ({ 11: "J", 12: "Q", 13: "K", 14: "A" })[card.value] || String(card.value);
  await page.getByRole("button", { name: `${rank} of hearts — Standard playing card`, exact: true }).click();
  await page.getByRole("button", { name: `Swap ${rank} of hearts for ${card.name}`, exact: true }).click();
  await expect(page.locator(".deck-slot-preview img")).toHaveAttribute("src", /sheen-raincall-mender-hearts\.webp\?v=2$/);
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(1);
  await expect(page.locator(".deck-preview-copy")).toContainText("Clean block: Heal 1.");
  await page.locator(".deck-inspection-rail").getByText("Full rules & keywords", { exact: true }).click();
  await expect(page.locator(".deck-inspection-rail .card-rules-details")).toContainText("After this blocks, gain 1 life");
  await expect(page.locator(".deck-inspection-rail").getByRole("link", { name: "Read keyword guide" })).toHaveAttribute("href", "/card-keywords.html#sheen-raincall-mender");
  await page.locator(".deck-settings > summary").click();
  await page.getByRole("button", { name: "Obsidian deck box", exact: true }).click();
  await page.locator(".deck-settings > summary").click();
  await page.getByLabel("Deck name", { exact: true }).fill("Sheen in Obsidian");
  await page.getByRole("button", { name: "Create Deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save New Version", exact: true })).toBeEnabled();
  const getSaved = () => JSON.parse(fs.readFileSync(storePath, "utf8")).accounts.find((entry) => entry.id === account.id).stats.savedConstructedDeck;
  expect(getSaved().cardSuitChoices[card.id]).toEqual(["hearts"]);
  expect(getSaved().deckBoxId).toBe("obsidian");
  await page.getByRole("button", { name: `${rank} of hearts — ${card.name}`, exact: true }).click();
  const out = path.resolve(__dirname, "../docs/generated-assets/workshop-compact-review");
  fs.mkdirSync(out, { recursive: true });
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "deck-workshop-desktop.png") });
  await page.screenshot({ path: path.join(out, "deck-workshop-page.png"), fullPage: true });
  const resizer = page.getByRole("separator", { name: "Resize card panel" });
  const originalWidth = (await page.locator(".deck-inspection-rail").boundingBox()).width;
  await resizer.focus();
  await page.keyboard.press("ArrowLeft");
  await expect(resizer).toHaveAttribute("aria-valuenow", "310");
  expect((await page.locator(".deck-inspection-rail").boundingBox()).width).toBeGreaterThan(originalWidth);
  const handle = await resizer.boundingBox();
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle.x + handle.width / 2 - 30, handle.y + handle.height / 2);
  await page.mouse.up();
  await expect(resizer).toHaveAttribute("aria-valuenow", "340");
  await page.getByRole("button", { name: "Cards", exact: true }).click();
  await expect(page.locator(".deck-slot.is-replaced img")).toHaveAttribute("src", /sheen-raincall-mender-hearts\.webp\?v=2$/);
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.locator(".deck-slot-preview")).toHaveCount(0);
  await expect(page.getByRole("button", { name: `Restore standard ${rank}♥`, exact: true })).toBeVisible();
  await page.reload();
  await page.locator('button[data-area="build"]').click();
  await page.getByRole("button", { name: "Open Collection Workshop" }).click();
  await page.getByRole("tab", { name: "Decks", exact: true }).click();
  await expect(page.getByRole("button", { name: "Cards", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "Preview", exact: true })).toHaveAttribute("aria-pressed", "false");
  await expect(resizer).toHaveAttribute("aria-valuenow", "340");
  await page.getByRole("button", { name: "Compact", exact: true }).click();
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await page.getByRole("button", { name: `${rank} of hearts — ${card.name}`, exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator(".deck-workshop")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "deck-workshop-mobile.png") });
  await page.getByRole("button", { name: `Restore standard ${rank}♥`, exact: true }).click();
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(0);
  await page.getByRole("button", { name: "Save New Version", exact: true }).click();
  await expect(() => expect(getSaved().replacementCount).toBe(0)).toPass({ timeout: 10000 });
  await page.getByRole("button", { name: "New deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Create Deck", exact: true })).toBeEnabled();
  await expect(page.getByLabel("Deck name", { exact: true })).toHaveValue("Rumin Constructed Deck");
  await page.getByLabel("Deck faction", { exact: true }).selectOption("mekan");
  await page.locator(".deck-settings > summary").click();
  await page.getByLabel("Deck General", { exact: true }).selectOption("hui");
  await page.getByLabel("Deck name", { exact: true }).fill("Mekan Hui");
  await page.getByRole("button", { name: "Create Deck", exact: true }).click();
  await expect(page.getByRole("button", { name: "Save New Version", exact: true })).toBeEnabled();
  expect(getSaved().generalId).toBe("hui");
  await page.getByRole("tab", { name: "Packs", exact: true }).click();
  await page.getByRole("radio", { name: /Theatrical/ }).check();
  const packResponse = page.waitForResponse((response) => response.url().endsWith("/api/collection/open-pack") && response.request().method() === "POST");
  await page.getByRole("button", { name: "Open Earned Pack", exact: true }).first().click();
  const { openedCards } = await (await packResponse).json();
  expect(openedCards.length).toBeGreaterThan(0);
  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: "Pause", exact: true }).click();
  await expect(dialog.getByRole("status")).toHaveText(/Breaking the seal/);
  await dialog.getByRole("button", { name: "Next card", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("uncommon");
  await dialog.screenshot({ path: path.join(out, "pack-opening-mobile.png") });
  await page.setViewportSize({ width: 1366, height: 900 });
  await dialog.screenshot({ path: path.join(out, "pack-opening-desktop.png") });
  await dialog.getByRole("button", { name: "Reveal all", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".pack-opened-cards article")).toHaveCount(openedCards.length);
  expect(errors).toEqual([]);
});
