const { test, expect } = require("@playwright/test");
const fs = require("node:fs");
const path = require("node:path");
const AxeBuilder = require("@axe-core/playwright").default;
const { COLLECTION_CARDS } = require("../server/gameContent");
const DRONE_ART = require("../server/contentAssetManifest.json").entries.find((entry) => entry.source === "/assets/gauntlet/constructed/faces/bizi-dune-circuit-runner-hearts.webp").path;

test("matching cards switch views and zoom without changing the deck, on desktop and mobile", async ({ page, request, baseURL }) => {
  const response = await request.post("http://127.0.0.1:4104/api/auth/register", { data: { name: `Gallery QA ${Date.now()}`, password: "Local-Gallery-Review-42" } });
  expect(response.ok()).toBeTruthy();
  const session = await response.json();
  const card = COLLECTION_CARDS.find((entry) => entry.name === "Aerial Drone");
  const storePath = path.resolve(__dirname, "../.playwright-data/slot-workshop/accounts.json");
  const store = JSON.parse(fs.readFileSync(storePath, "utf8"));
  const collection = store.accounts.find((entry) => entry.id === session.account.id).stats.collection;
  collection.gameplayEntitlements = Object.fromEntries(COLLECTION_CARDS.map((entry) => [entry.id, 1]));
  collection.collectorVariants = { [`${card.id}:collector-foil`]: 1 };
  fs.writeFileSync(storePath, JSON.stringify(store));
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.addInitScript((token) => localStorage.setItem("gauntlet_auth_token", token), session.token);
  const openWorkshop = async () => {
    await page.goto(baseURL);
    await page.locator('button[data-area="build"]').click();
    await page.getByRole("button", { name: "Open Collection Workshop" }).click();
    await page.getByRole("tab", { name: "Decks", exact: true }).click();
    await page.getByLabel("Deck faction", { exact: true }).selectOption("bizi");
    await page.getByRole("button", { name: "4 of hearts — Standard playing card", exact: true }).click();
  };
  await openWorkshop();
  const matching = page.getByRole("region", { name: "Replacements for 4 of hearts" });
  const icons = matching.getByRole("button", { name: "Icons", exact: true });
  const list = matching.getByRole("button", { name: "List", exact: true });
  const zoom = matching.getByRole("button", { name: "Zoom matching card Aerial Drone", exact: true });
  const dialog = page.getByRole("dialog", { name: "Aerial Drone", exact: true });
  const close = page.getByRole("button", { name: "Close card zoom" });
  const out = path.resolve(__dirname, "../.eggs/evidence/workshop-gallery-review");
  fs.mkdirSync(out, { recursive: true });
  await expect(icons).toHaveAttribute("aria-pressed", "true");
  await expect(matching.locator(".deck-candidate-art img")).toHaveAttribute("src", DRONE_ART);
  await expect(page.getByRole("button", { name: "Compact", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.locator(".deck-slot-preview")).toHaveCount(0);
  await zoom.click();
  await expect(dialog).toBeVisible();
  await expect(dialog.locator(".deck-card-zoom-art img")).toHaveAttribute("src", DRONE_ART);
  await expect(dialog).toContainText(card.displayText);
  await expect(close).toBeFocused();
  await page.keyboard.press("Shift+Tab");
  expect(await dialog.evaluate((node) => node.contains(document.activeElement))).toBe(true);
  await page.keyboard.press("Tab");
  await expect(close).toBeFocused();
  expect((await new AxeBuilder({ page }).include(".deck-card-zoom").analyze()).violations).toEqual([]);
  await dialog.locator(".deck-card-zoom-art img").click();
  await expect(dialog).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(zoom).toBeFocused();
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(0);
  await list.click();
  await expect(matching.locator(".deck-candidate-art")).toHaveCount(0);
  await zoom.click();
  await close.click();
  await expect(zoom).toBeFocused();
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "list-desktop.png") });
  await openWorkshop();
  await expect(list).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "Preview", exact: true })).toHaveAttribute("aria-pressed", "false");
  await icons.click();
  await matching.getByRole("button", { name: "Preview Aerial Drone", exact: true }).click();
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(0);
  await page.getByLabel("Aerial Drone card version", { exact: true }).selectOption(`${card.id}:collector-foil`);
  await expect(matching.locator(".is-animated-collector")).toHaveAttribute("data-collector-style", "charged-engine");
  await page.emulateMedia({ reducedMotion: "reduce" });
  const swapBounds = await matching.getByRole("button", { name: "Swap 4 of hearts for Aerial Drone", exact: true }).boundingBox();
  const railBounds = await page.locator(".deck-inspection-rail").boundingBox();
  expect(swapBounds.y + swapBounds.height).toBeLessThanOrEqual(railBounds.y + railBounds.height);
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "icons-desktop.png") });
  await zoom.click();
  await expect(dialog.locator(".is-animated-collector")).toHaveAttribute("data-collector-style", "charged-engine");
  await expect(dialog.locator(".collector-card-sheen")).toHaveCSS("animation-name", "none");
  await page.screenshot({ path: path.join(out, "zoom-desktop.png") });
  const bounds = await dialog.boundingBox();
  expect(bounds.width).toBeGreaterThan(700);
  await page.mouse.click(4, 4);
  await expect(dialog).toHaveCount(0);
  await expect(zoom).toBeFocused();
  await matching.getByRole("button", { name: "Swap 4 of hearts for Aerial Drone", exact: true }).click();
  await expect(page.locator(".deck-slot")).toHaveCount(52);
  await expect(page.locator(".deck-slot.is-replaced")).toHaveCount(1);
  await page.getByRole("button", { name: "Zoom Aerial Drone", exact: true }).click();
  await expect(dialog).toBeVisible();
  await close.click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator(".deck-workshop").screenshot({ path: path.join(out, "icons-mobile.png") });
  await zoom.click();
  await expect(dialog).toBeVisible();
  const mobile = await dialog.boundingBox();
  expect(mobile.x).toBeGreaterThanOrEqual(0);
  expect(mobile.x + mobile.width).toBeLessThanOrEqual(390);
  expect(mobile.y + mobile.height).toBeLessThanOrEqual(844);
  expect(await dialog.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true);
  await page.screenshot({ path: path.join(out, "zoom-mobile.png") });
  await close.click();
  await expect(zoom).toBeFocused();
  await page.getByRole("button", { name: "5 of hearts — Standard playing card", exact: true }).click();
  await page.getByRole("button", { name: "Zoom 5 of hearts", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "5 of hearts", exact: true })).toBeVisible();
  await expect(page.locator(".deck-card-zoom-art img")).toHaveAttribute("alt", "5 of hearts standard playing card");
  await close.click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe("hidden");
  expect(errors).toEqual([]);
});

test("neutral cards keep their own faction in every workshop view and keyword deep link", async ({ page, request, baseURL }) => {
  const response = await request.post("http://127.0.0.1:4104/api/auth/register", { data: { name: `Faction QA ${Date.now()}`, password: "Local-Faction-Review-42" } });
  expect(response.ok()).toBeTruthy();
  const session = await response.json();
  const card = COLLECTION_CARDS.find((entry) => entry.factionId === "neutral");
  const storePath = path.resolve(__dirname, "../.playwright-data/slot-workshop/accounts.json");
  const store = JSON.parse(fs.readFileSync(storePath, "utf8"));
  store.accounts.find((entry) => entry.id === session.account.id).stats.collection.gameplayEntitlements = { [card.id]: 1 };
  fs.writeFileSync(storePath, JSON.stringify(store));
  await page.addInitScript((token) => localStorage.setItem("gauntlet_auth_token", token), session.token);
  await page.goto(baseURL);
  await page.locator('button[data-area="build"]').click();
  await page.getByRole("button", { name: "Open Collection Workshop" }).click();
  await page.getByRole("tab", { name: "Decks", exact: true }).click();
  const rank = ({ 11: "J", 12: "Q", 13: "K", 14: "A" })[card.value] || String(card.value);
  const slot = `${rank} of ${card.suit}`;
  await page.getByRole("button", { name: `${slot} — Standard playing card`, exact: true }).click();
  const matching = page.locator(".deck-candidate");
  await expect(matching.locator(".deck-card-faction")).toHaveText("Neutral");
  await matching.getByRole("button", { name: `Preview ${card.name}`, exact: true }).click();
  await expect(page.locator(".deck-preview-copy .deck-card-faction")).toHaveText("Neutral");
  await expect(page.locator(".deck-preview-copy")).toContainText("Usable in any faction");
  await page.getByRole("button", { name: "List", exact: true }).click();
  await expect(matching.locator(".deck-card-faction")).toHaveText("Neutral");
  await matching.getByRole("button", { name: `Swap ${slot} for ${card.name}`, exact: true }).click();
  const replacement = page.locator(".deck-slot.is-replaced");
  await expect(replacement.locator(".deck-card-faction")).toHaveText("Neutral");
  await expect(replacement).toHaveAccessibleDescription("Neutral");
  await page.getByRole("button", { name: "Cards", exact: true }).click();
  await expect(replacement.locator(".deck-card-faction")).toHaveText("Neutral");
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.locator(".deck-slot-preview")).toHaveCount(0);
  await expect(page.locator(".deck-preview-copy .deck-card-faction")).toBeVisible();
  const out = path.resolve(__dirname, "../.eggs/evidence/card-faction-labels");
  fs.mkdirSync(out, { recursive: true });
  for (const width of [1366, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await page.getByRole("button", { name: `Zoom ${card.name}`, exact: true }).click();
    const dialog = page.getByRole("dialog", { name: card.name, exact: true });
    await expect(dialog.locator(".deck-card-faction")).toHaveText("Neutral");
    await expect(dialog).toContainText("Usable in any faction");
    await dialog.screenshot({ path: path.join(out, `neutral-zoom-${width}.png`) });
    await page.getByRole("button", { name: "Close card zoom" }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
  }
  for (const width of [1366, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await page.goto(`${baseURL}/card-keywords.html#${card.id}`);
    const entry = page.locator(`article[id="${card.id}"]`);
    await expect(entry.locator(".card-faction")).toHaveText("Faction: Neutral · Usable in any faction");
    await expect(entry.locator(".card-faction")).toBeInViewport();
    await expect(page.locator("article .card-faction")).toHaveCount(COLLECTION_CARDS.length);
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await entry.screenshot({ path: path.join(out, `keyword-${width}.png`) });
  }
});
