/** Finite handlers implemented by this deployed engine. Runtime validation is authoritative. */
export type CardEffectId = "gilded-scale-legionary" | "forum-ledger-runner" | "vault-shield-bearer" | "coin-scale-spear" | "senate-vault-guard" | "marble-market-tribune" | "rumie-vault-shield" | "imperial-scale-pike" | "aurelian-clawblade" | "basilisk-standard" | "jewel-bank-contract" | "tax-road-scout" | "marble-phalanx" | "counting-house-aegis" | "triumphal-ram" | "edict-of-the-vault" | "kaisers-gold-claw" | "rumie-market-colossus" | "rootwatch-initiate" | "quiet-grove-sentinel" | "mossbound-staff" | "living-bark-guard" | "beli-vinebinder" | "harmony-ward" | "thornroot-counterstroke" | "beli-canopy-shield" | "nus-verdant-edict" | "roots-that-remember" | "tangs-patient-hand" | "seedwall-acolyte" | "raincall-mender" | "ringroot-bastion" | "sapling-chorus" | "nus-calm-command" | "emperors-heartwood" | "beli-awakened" | "deckhand-diver" | "tideglass-cutlass" | "sunken-coin" | "coral-hull-guard" | "riptide-smuggler" | "lafayettes-chart" | "pressure-lock-pistol" | "ristus-blackwake" | "captains-bad-wager" | "poleas-sunken-order" | "leviathan-salvage" | "kelpcloak-trickster" | "ballast-hook" | "tide-debt-ledger" | "abyssal-switchboard" | "poleas-moonlit-map" | "the-last-gamble" | "ristus-rises" | "copperline-technician" | "voltage-ration" | "dune-circuit-runner" | "gearplate-shield" | "heras-calibration" | "solar-array-adept" | "constanti-conduit" | "sandstorm-processor" | "focus-overclock" | "regnum-voltage-bank" | "desert-logic-engine" | "brass-spark" | "railspike-marshal" | "heat-sink-matrix" | "clockwork-caravan" | "voltaric-ultimatum" | "focus-prime-signal" | "constanti-sunforge";
export interface CardEffect { readonly id: CardEffectId; readonly version: 1; readonly parameters: Readonly<Record<string, number>>; }
export interface FactionMechanics { readonly id: "imperial-rhythm" | "living-defense" | "sunken-maneuvers" | "acceleration-network"; readonly version: 1; readonly parameters: Readonly<Record<string, number>>; }
export interface BossAbility { readonly id: "first-strike" | "odd-pressure" | "even-feint" | "final-push" | "late-pressure" | "first-and-final"; readonly title: string; readonly text: string; readonly name: string; readonly tier: 1 | 2 | 3; readonly evenBonus?: number; readonly healAtTurnStart?: number; }
export interface EncounterSetup { readonly version: 1; readonly bossLife: number; readonly attacksPerTurn: number; readonly minAttackValue: number; readonly maxAttackValue: number; readonly chapterNumber: number; readonly bossAbility: BossAbility; readonly playerAdditions: readonly string[]; readonly bossAdditions: readonly string[]; readonly attackTiming: "clear-priority"; readonly winRoute: "first-uncompleted"; readonly lossRoute: "retry"; }
export interface GameConfig { readonly version: 1; readonly startingLife: 42; readonly handSize: number; }
export interface ContentBinding { readonly authoredRelease: string; readonly rulesVersion: string; readonly cardEffectContractVersion: "gauntlet.card-effects.v1"; readonly factionEffectContractVersion: "gauntlet.faction-effects.v1"; readonly encounterContractVersion: "gauntlet.encounter-setup.v1"; readonly assetManifestVersion: string; readonly gameConfigVersion: "gauntlet.game-config.v1"; }
export interface CardPresentation { readonly releaseId: string; readonly assetManifestVersion: string; readonly illustration?: string | null; readonly faces?: Readonly<Record<string, string | null>>; readonly face?: string | null; readonly composed: boolean; readonly illustrationAssetId?: string | null; readonly illustrationDigest?: string | null; }
